### ISSUE TITLE
Create Demo Script for Unzipping/ accessing data

### ISSUE THREAD

**Issue by SamStruthers** [rossyndicate/CPF_reservoir_study_data#2]
Matt used the code:
 download.file('[https://zenodo.org/record/8308733/files/rossyndicate/CPF_reservoir_study_data-latest.zip?download=1'](https://zenodo.org/record/8308733/files/rossyndicate/CPF_reservoir_study_data-latest.zip?download=1%27),               destfile = 'clp.zip') unzip('clp.zip') list.files('rossyndicate-CPF_reservoir_study_data-df3e86d/data') library(tidyverse) z <- read_csv('rossyndicate-CPF_reservoir_study_data-df3e86d/data/cleaned/CPF_reservoir_chemistry_up_to_071023.csv')

as a demo in class to play with our data. We should create a script that demo's the best way to download this data and have it in the readME file for the next release. @kathryn-willi  or @steeleb , thoughts on the best way to do this?

**Comment by SamStruthers** [comment]
@kathryn-willi If you have a sec today, can you review the `demo.R` script in the scripts folder. If the code looks good, I'll add it to bottom of ReadMe file and re release alongside dataset when I have more data from RMRS. 

Meant to open a PR but forgot that I was working in main rather than my own branch.

**Comment by steeleb** [comment]
It does look like both read.table and read_csv [will support reading zip files without unzipping](https://stackoverflow.com/questions/12460938/r-reading-in-a-zip-data-file-without-unzipping-it). But if there are multiple files, I'm unsure of how it behaves. If you want all the files, then you *might* be able to map the read_csv or read.table.

Does that help? Or are you searching for a solution to a different problem? :)
